In [4]:
import numpy as np
np.random.seed(42)
A = np.random.randint(1, 10, size=(4, 3))
B = np.random.randint(1, 10, size=(3, 5))

print("Matrix A:\n", A, "\nShape: ", A.shape)
print("\nMatrix B:\n", B, "\nShape: ", B.shape)

Matrix A:
 [[7 4 8]
 [5 7 3]
 [7 8 5]
 [4 8 8]] 
Shape:  (4, 3)

Matrix B:
 [[3 6 5 2 8]
 [6 2 5 1 6]
 [9 1 3 7 4]] 
Shape:  (3, 5)


In [5]:
assert A.shape[1] == B.shape[0], "Inner Dimensions do not match!"
C = A@B
print("Matrix C:\n", C)
print("\nShape of C:", C.shape)
assert C.shape == (4, 5)

Matrix C:
 [[117  58  79  74 112]
 [ 84  47  69  38  94]
 [114  63  90  57 124]
 [132  48  84  72 112]]

Shape of C: (4, 5)


In [6]:
total_sum = np.sum(C)
row_sums = np.sum(C, axis=1)
col_sums = np.sum(C, axis=0)

print("Total sum of C:", total_sum)
print("Row-wise sums:", row_sums)
print("Column-wise sums:", col_sums)

Total sum of C: 1668
Row-wise sums: [440 332 448 448]
Column-wise sums: [447 216 322 241 442]
